###############################################################################
## Stigmee: A 3D browser and decentralized social network.
## Copyright 2021 Quentin Quadrat <lecrapouille@gmail.com>
##
## This file is part of Stigmee.
##
## Stigmee is free software: you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################
##
## This is a modification of https://github.com/dsaltares/godot-wild-jam-18
## Under the Apache-2.0 License. For more information see his blog at this link
## https://saltares.com/continuous-delivery-pipeline-for-godot-and-itch.io/
##
###############################################################################

name: Export Godot project and publish on GitHub
on:
  workflow_dispatch:
    branches:
      - master
      - dev-example
    paths:
      - 'stigmee/**'

jobs:
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    name: Exporting Stigmee
    env: # FIXME: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecur
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
    - name: checkouting Stigmee
      uses: actions/checkout@v2.3.1

    - name: Installing system packages for compiling Godot-cpp
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev \
             libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm

    - name: Installing Godot modules
      uses: actions/checkout@v2.3.1
      with:
        repository: stigmee/godot-modules
        ref: dev-lecrapouille
        token: ${{ secrets.ACCESS_TOKEN }}
        path: godot-modules
        
    - name: Compiling Godot modules
      run: cd $GITHUB_WORKSPACE/godot-modules && ./build.sh
      
    - name: Linking generated lib, assets to make Godot find them
      run: ln -s $GITHUB_WORKSPACE/godot-modules/build $GITHUB_WORKSPACE/stigmee/build

    - name: exporting Stigmee
      uses: firebelley/godot-export@v3.0.0
      with:
        base_version: 0.1.0
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4/Godot_v3.4-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4/Godot_v3.4-stable_export_templates.tpz
        relative_project_path: ./stigmee
        archive_export_output: true
      env:
        GITHUB_TOKEN: ${{ secrets.EXPORT_GITHUB_TOKEN }}
